server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: local
  messages:
    # 国际化资源文件路径
    basename: messages
  #jackson:
    # 默认就是UTC时区
    #time-zone: UTC
    # 加上这个配置，从前台接收LocalDateTime类型可直接使用@DateTimeFormat注解
    #date-format: yyyy-MM-dd HH:mm:ss
