server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: dev
  messages:
    # 国际化资源文件路径
    basename: messages
  jackson:
    time-zone: GMT+8
    # 加上这个配置，从前台接收LocalDateTime类型可直接使用@DateTimeFormat注解
    date-format: yyyy-MM-dd HH:mm:ss
