# http://localhost:8080/actuator/info
info:
  app:
    groupId: @project.groupId@
    artifactId: @project.artifactId@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    java:
      source: @java.version@
      target: @java.version@
    quickboot: @quickboot.version@
    springboot: @springboot.version@
spring:
  devtools:
    restart:
      enabled: true
  mvc:
    throw-exception-if-no-handler-found: false
  resources:
    # 对于Restful风格的应用应该设置为false; 对于传统的应用（如: 使用thymeleaf），应该设置为 true
    add-mappings: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    # 以本地文件存储数据的方式使用H2数据库。
    # ./h2/test 在项目根路径下保存数据库文件
    # AUTO_SERVER=true 启动自动混合模式，允许开启多个连接，该参数不支持在内存中运行模式
    # DB_CLOSE_ON_EXIT 当虚拟机退出时并不关闭数据库
    url: jdbc:h2:file:./h2/test;AUTO_SERVER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    # 以内存方式使用数据库（这里会创建一个数据库名为 test 的数据库实例）
    # MODE=MYSQL 兼容模式
    # url: jdbc:h2:mem:test;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      # 是否允许网页访问，默认false
      enabled: true
      # h2数据库的访问路径：http://localhost:8080/h2（默认为/h2-console）
      path: /h2
      settings:
        # 是否允许从其他地方访问，还是只允许从本地访问
        web-allow-others: true
#日志配置
logging:
  file: logs/app.log
  level:
    root: info
    com.github.mengweijin: debug
decorator:
  datasource:
    enabled: true
    p6spy:
      # Register P6LogFactory to log JDBC events
      enable-logging: true
      # Use com.p6spy.engine.spy.appender.MultiLineFormat instead of com.p6spy.engine.spy.appender.SingleLineFormat
      multiline: true
      # Use logging for default listeners [slf4j, sysout, file]
      logging: slf4j
      # Log file to use (only with logging=file)
      #log-file: spy.log
      # Custom log format, if specified com.p6spy.engine.spy.appender.CustomLineFormat will be used with this log format
      #log-format:
      tracing:
        include-parameter-values: true
